# Generated by Django 3.2.15 on 2022-11-09 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='registration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstname', models.CharField(max_length=100)),
                ('lastname', models.CharField(max_length=100)),
                ('emailid', models.EmailField(max_length=100)),
                ('password', models.CharField(max_length=100)),
                ('dateofbirth', models.DateField()),
                ('mobilenumber', models.CharField(max_length=100)),
                ('role', models.CharField(max_length=100)),
                ('gender', models.CharField(max_length=50)),
                ('question', models.CharField(max_length=200)),
                ('answer', models.CharField(max_length=200)),
                ('question1', models.CharField(max_length=200)),
                ('answer1', models.CharField(max_length=200)),
                ('question2', models.CharField(max_length=200)),
                ('answer2', models.CharField(max_length=200)),
            ],
        ),
    ]
