# Generated by Django 3.2.15 on 2022-10-20 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Weatherdetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city', models.CharField(max_length=100)),
                ('temperature', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=100)),
                ('humidity', models.CharField(max_length=100)),
                ('pressure', models.CharField(max_length=100)),
                ('country', models.CharField(max_length=100)),
                ('sunrise', models.CharField(max_length=100)),
                ('sunset', models.CharField(max_length=100)),
                ('windspeed', models.CharField(max_length=100)),
            ],
        ),
    ]
